version: '3.8'
services:
  postgres:
    image: postgres
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_USER: joe_k
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: fetch_interview
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
